# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c48646fd71432378f79756e6150333db5b50af77a61c433543bbc433986d88c3c194bd57c1171e36300dc089a6f90ce5106638b3fcfe64f6673d6e2d6ed1d40f

test:
  secret_key_base: 6b1b97d393466129a89f7b21adc4ccf0723c97ddebb06cd530bda2dc8bb5f7e87bde4d0842bb7c5b4d7213e9d5b2e2d8902eea4e59a1051352f2506cb34068a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
